// create a new subreddit
import { fetchWrapper, handleStrings } from "@lib/helpers";
import AlertTriangle from "@public/icons/alert-triangle.svg";
import styles from "@styles/Default.module.scss";
import type { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Link from "next/link";
import { FormEvent, useState } from "react";

const LogInPage: NextPage = () => {
  const [alert, setAlert] = useState<string | null>(null);
  const [form, setForm] = useState({
    name: "",
    password: "",
  });

  const router = useRouter();

  const handleForm = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const user = {
      ...form,
      uri: handleStrings.alphaNum(form.name),
    };
    fetchWrapper
      .post("/api/users", user)
      .then((data) => router.push(`/u/${data.user.uri}`))
      .catch((error) => setAlert(error));
  };

  return (
    <div className={styles.root}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <form className={styles.form} onSubmit={handleForm}>
          <div className={styles.heading}>
            <h1>Sign Up</h1>
            <div>
              <Link href="/login">
                <a className={styles.link}>LOGIN</a>
              </Link>
            </div>
          </div>
          <fieldset>
            <input
              autoComplete="off"
              id="uri"
              name="uri"
              onChange={(e) =>
                setForm((state) => ({
                  ...state,
                  uri: handleStrings.alphaNum(e.target.value),
                }))
              }
              placeholder="Username"
              required
              type="text"
            />
          </fieldset>
          <fieldset>
            <input
              autoComplete="off"
              id="password"
              name="password"
              onChange={(e) =>
                setForm((state) => ({
                  ...state,
                  password: e.target.value,
                }))
              }
              placeholder="Password"
              required
              type="password"
            />
          </fieldset>
          {alert && (
            <div className={styles.alert}>
              <span className={styles.icon}>
                <AlertTriangle width={16} height={16} />
              </span>
              {alert}
            </div>
          )}
          <button className={styles.button}>SIGN UP</button>
        </form>
      </div>
    </div>
  );
};

export default LogInPage;
