// top posts from all subs
import { Layout } from "@components";
import { rAll } from "@lib/constants";
import { fetchWrapper } from "@lib/helpers";
import { IPost } from "@lib/interfaces";
import styles from "@styles/Default.module.scss";
import type { GetStaticProps, NextPage } from "next";
import getConfig from "next/config";
import Head from "next/head";

const { publicRuntimeConfig } = getConfig();
const baseUrl = `${publicRuntimeConfig.apiUrl}`;

export const getStaticProps: GetStaticProps = async (context) => {
  const posts: IPost[] = await fetchWrapper
    .get(`${baseUrl}/posts`)
    .catch((error) => console.error(error));
  const props = { ...posts };
  return { props: { ...props } };
};

interface IAllPage {
  posts: IPost[];
}

const AllPage: NextPage<IAllPage> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Link href="/r/create">
          <a className={styles.button}>CREATE COMMUNITY</a>
        </Link> */}
      <Layout sub={rAll} posts={posts} />
    </div>
  );
};

export default AllPage;
