// top posts from all subs
import { useGlobalStateValue } from "@components";
import { fetchWrapper } from "@lib/helpers";
import { IPost } from "@lib/interfaces";
import styles from "@styles/Default.module.scss";
import type { GetStaticProps, NextPage } from "next";
import getConfig from "next/config";
import Head from "next/head";
import Link from "next/link";

const { publicRuntimeConfig } = getConfig();
const baseUrl = `${publicRuntimeConfig.apiUrl}`;

export const getStaticProps: GetStaticProps = async (context) => {
  const posts: IPost[] = await fetchWrapper
    .get(`${baseUrl}/posts`)
    .catch((error) => console.error(error));
  const props = { ...posts };
  return { props: { ...props } };
};

interface IAllPage {
  posts: IPost[];
}

const AllPage: NextPage<IAllPage> = ({ posts }) => {
  const [{ theme }, dispatch] = useGlobalStateValue();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => dispatch({ type: "theme", payload: "🎃🎃🎃" })}>
        dark mode
      </button>
      <div>
        <Link href="/r/create">
          <a className={styles.button}>CREATE COMMUNITY</a>
        </Link>
        <pre>{JSON.stringify({ posts }, null, 2)}</pre>
      </div>
    </div>
  );
};

export default AllPage;
