// top posts from all subs
import { Layout } from "@components";
import { rAll } from "@lib/constants";
import { fetchWrapper } from "@lib/helpers";
import { IPost, ISub } from "@lib/interfaces";
import styles from "@styles/Default.module.scss";
import type { GetStaticProps, NextPage } from "next";
import getConfig from "next/config";
import Head from "next/head";
import Link from "next/link";

const { publicRuntimeConfig } = getConfig();
const baseUrl = `${publicRuntimeConfig.apiUrl}`;

export const getStaticProps: GetStaticProps = async (context) => {
  const posts: IPost[] = await fetchWrapper
    .get(`${baseUrl}/posts`)
    .catch((error) => console.error(error));
  const subs: ISub[] = await fetchWrapper.get(`${baseUrl}/subs`);
  const props = { ...posts, ...subs };
  return { props: { ...props } };
};

interface IAllPage {
  posts: IPost[];
  subs: IPost[];
}

const AllPage: NextPage<IAllPage> = ({ posts, subs }) => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Link href="/r/create">
          <a className={styles.button}>CREATE COMMUNITY</a>
        </Link> */}
      <div className={styles.header}>
        {subs.map((sub) => {
          return (
            <div key={sub._id as string}>
              <Link href={`/r/${sub.uri}`}>
                <a>r/{sub.uri}</a>
              </Link>
            </div>
          );
        })}
      </div>
      <Layout sub={rAll} posts={posts} />
    </div>
  );
};

export default AllPage;
